.TH + 1 "November 2023" "1.0" "+ manual page"
.SH NAME
+ \- compile a file to an executable with the same name but without .cpp.

.SH SYNOPSIS
.B +
.I file

.SH DESCRIPTION
This compile a file to an executable with the same name but without .cpp.

.SH EXAMPLES
Compile a file named test.cpp to an executable named test.
.PP
+ test.cpp

.SH AUTHOR
Slash.