.TH mycommand 1 "November 2023" "1.0" "t manual page"
.SH NAME
mycommand \- create a file and enter it with visual studio code.

.SH SYNOPSIS
.B t
.I file

.SH DESCRIPTION
This create a file and enter it with visual studio code.

.SH EXAMPLES
Create a file named index.html and enter it with visual studio code.
.PP
t index.html

.SH AUTHOR
Slash.