#!/bin/bash

if [ $# -eq 0 ] || [ -z "$1" ]; then
    echo "Usage: + [source_file.cpp]"
    exit 1
fi

source_file="$1"
executable_file="${source_file%.cpp}"

g++ -o "$executable_file" "$source_file"
echo -e "${output_color} ${executable_file} created${reset_color}"