#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: t [filename]"
    exit 1
fi

filename="$1"

if [ -e "$filename" ]; then
    echo "'$filename' already exists."
else
    touch "$filename"
    echo -e "${output_color} ${filename} created.${reset_color}"
    code "$filename"
fi